### PR TITLE
fix: ko version output

### LINKED ISSUE #151: error during command execution:unknown command "0.11.2" for "ko"
#### What would you like to be added:

`EnsureKo` method throws the following error when you type `$ go run mage.go BuildImagesLocal`:

```sh
Building image with ko for local test...
Checking if `ko` version 0.11.2 is installed
Error: unknown command "0.11.2" for "ko"
Run 'ko --help' for usage.
2022/07/29 21:42:27 error during command execution:unknown command "0.11.2" for "ko"
Error: could not determine the installed version of /Users/batuhan.apaydin/go/bin/ko with '/Users/batuhan.apaydin/go/bin/ko 0.11.2': running "/Users/batuhan.apaydin/go/bin/ko 0.11.2" failed with exit code 1
exit status 1
```

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #151 

#### Does this PR introduce a user-facing change?

```release-note
fix: ko version output in magefile
```

### CODE REVIEW

**Comment by developer-guy** [comment]
Kindly ping @cpanato

File: magefile.go [hunk 1]
```diff
@@ -252,7 +252,7 @@ func EnsureKO(version string) error {
 	}
 
 	fmt.Printf("Checking if `ko` version %s is installed\n", versionToInstall)
-	found, err := pkg.IsCommandAvailable("ko", versionToInstall, "version")
+	found, err := pkg.IsCommandAvailable("ko", "version", "version")
```
Comment (cpanato) [inline magefile.go:255]: this should be
`found, err := pkg.IsCommandAvailable("ko", "version", versionToInstall)`
