### PR TITLE
Autodetect compressed tarballs and fix --scan-images flag

### LINKED ISSUE #36: Image layer code should inspect bytes instead of relying on file extension
#### What happened:

When extracting image layers, the layer analyzer will treat the blobs as a tar file or as compressed data depending on the file extension. This causes an error when the blobs are extracted and opened for inspection

#### What you expected to happen:

Layer blobs should be opened and inspected

#### How to reproduce it (as minimally and precisely as possible):

Trying to generate an SBOM with bom v0.2.0 of this Istio image fails:

```console
wget https://storage.googleapis.com/istio-prerelease/prerelease/1.13.0-beta.0/docker/app-debug.tar.gz
bom generate --image-archive app-debug.tar.gz

INFO Generating SPDX Bill of Materials            
INFO Processing tarball app-debug.tar.gz          
INFO Generating SPDX package from image tarball app-debug.tar.gz 
INFO Successfully extracted 12 files from image tarball app-debug.tar.gz 
INFO Package describes istio/app:1.13.0-beta.0-debug image 
INFO Image manifest lists 7 layers                
FATA generating doc: creating SPDX document: generating tarball package: getting os data from container: reading os type from layer: reading os release: extracting os-release from tar: reading tarfile: archive/tar: invalid tar header 

```

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR fixes two bugs:

1. Compressed tarballs are now autodetected and correctly handled by checking the first bytes in the header.  
2. There was a missing bit in the new --scan-images flag that missed some plumbing. Fixed now.

#### Which issue(s) this PR fixes:

Fixes #36

#### Does this PR introduce a user-facing change?

```release-note
- Tarball headers are now checked to see if they are compressed. Previously we relied on file extensions which made the tarball handling code flaky
- Fixed a proble where `--scan-images` was unresponsive because a bug in the internal plumbing 
```

### CODE REVIEW

**Review by kfaseela — APPROVED** [review]

**Comment by kfaseela** [comment]
lgtm thanks @puerco

File: pkg/osinfo/layer_scanner.go [hunk 1]
```diff
@@ -117,12 +116,26 @@ func (loss *LayerScanner) extractFileFromTar(tarPath, filePath, destPath string)
 	}
 	defer f.Close()
 
+	// Read the first bytes to determine if the file is compressed
+	var sample [2]byte
+	var compressed bool
+	if _, err := io.ReadFull(f, sample[:]); err != nil {
+		return errors.Wrap(err, "sampling bytes from tar header")
```
Comment (dims) [inline pkg/osinfo/layer_scanner.go:123]: `sampling initial bytes from file` (it's not tar we are looking for ...)

File: pkg/osinfo/layer_scanner.go [hunk 2]
```diff
@@ -117,12 +116,26 @@ func (loss *LayerScanner) extractFileFromTar(tarPath, filePath, destPath string)
...
+	}
+	if _, err := f.Seek(0, 0); err != nil {
+		return errors.Wrap(err, "rewinding read pointer")
+	}
+
+	if sample[0] == 31 && sample[1] == 139 {
```
Comment (dims) [inline pkg/osinfo/layer_scanner.go:129]: - Do you want to use the hex versions (easier to spot, like the ones https://github.com/golang/go/blob/master/src/compress/gzip/gunzip.go#L20-L22 )
- Do you want to sample 3 bytes? (looks like the 3rd byte is `0x08` for deflate)

File: pkg/osinfo/layer_scanner.go [hunk 3]
```diff
@@ -117,12 +116,26 @@ func (loss *LayerScanner) extractFileFromTar(tarPath, filePath, destPath string)
 	}
 	defer f.Close()
 
+	// Read the first bytes to determine if the file is compressed
+	var sample [2]byte
+	var compressed bool
```
Comment (dims) [inline pkg/osinfo/layer_scanner.go:121]: we are looking for gzip magic bytes, so `gzipped` may be better?

File: pkg/spdx/implementation.go [hunk 4]
```diff
@@ -86,8 +86,22 @@ func (di *spdxDefaultImplementation) ExtractTarballTmp(tarPath string) (tmpDir s
 	}
 	defer f.Close()
 
+	// Read the first bytes to determine if the file is compressed
+	var sample [2]byte
```
Comment (dims) [inline pkg/spdx/implementation.go:90]: same observations as above ... do we want to put this in a method that can be called from both places?

File: pkg/osinfo/layer_scanner.go (hunk 1 above)
Comment (puerco) [reply pkg/osinfo/layer_scanner.go]: Rephrased to file :+1:

File: pkg/osinfo/layer_scanner.go (hunk 2 above)
Comment (puerco) [reply pkg/osinfo/layer_scanner.go]: Nice suggestion, i've added it and added a link in a comment to the gunzip module for reference.

File: pkg/spdx/implementation.go (hunk 4 above)
Comment (puerco) [reply pkg/spdx/implementation.go]: Ah, yes I'm aware of this. I'm working on a PR to move this functionality to [our tar package](https://github.com/kubernetes-sigs/release-utils/blob/main/tar/tar.go) and once we cut a release there I will refactor all the tar code in the project.

File: pkg/osinfo/layer_scanner.go (hunk 3 above)
Comment (puerco) [reply pkg/osinfo/layer_scanner.go]: Renamed the var :+1:

**Comment by puerco** [comment]
Thanks a lot @dims I've addressed your comments, PTAL :)
