### PR TITLE
Disable local cache lookup, favor parallel download

### LINKED ISSUE #134: Multiarch images broken when generating sbom from local docker cache
#### What happened:

When generating an SBOM for a multi-arch image from the local docker cache, the SBOM is not only invalid but it describes only one arch.

#### What you expected to happen:

I would expect the SBOM to describe all the architectures, just as with the remote images

#### How to reproduce it (as minimally and precisely as possible):

Running the following will yield a valid `right.spdx` SBOM describing all the images and an invalid `wrong.spdx` sbom which not only does not validate but only has information about the local platform image:

```bash 
# First pulll a multi-arch image to local cache and generate an sbom
docker pull nginx:latest
bom generate -i nginx:latest > wrong.spdx

# Now generate the SBOM from the remote image:
docker rmi nginx:latest
bom generate -i nginx:latest > right.spdx
```

#### Anything else we need to know?:

To mitigate, the local docker cache needs to not have an image in order to generate its SBOM (as shown above)

#### Environment:
 bom v0.3.0

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR disables the local daemon lookup of container images to fix #134. 

When passing a reference to a multiarch image to the local docker daemon, the reference gets transalated to the local arch image, generating an SBOM only for the image corresponding to the local architecture. 

This PR reverts the local daemon change as apparently there is no way to get the docker daemon to return the correct reference (to the image index ) to GGCR.

In order to improve image download times the blob downloads to local tarballs are now parallelized which should at least provide some speed gains.

#### Which issue(s) this PR fixes:

Fixes #134

#### Special notes for your reviewer:

/cc @kubernetes-sigs/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
- Looking for precached images in the local daemon is now removed as it broke multiarch image SBOMs
- Image downloading is now done in parallel. This should provide some speed gains in some high bandwidth settings
```

### CODE REVIEW

File: pkg/spdx/implementation.go [hunk 1]
```diff
@@ -395,84 +331,56 @@ func (di *spdxDefaultImplementation) PullImagesToArchive(
...
 			}
 
-			logrus.Infof("Checking the local image cache for %s", refData.Tag)
-
-			img, err := daemon.Image(tagRef)
-			if err != nil {
-				return nil, fmt.Errorf("getting image %s: %w", referenceString, err)
+			d, ok := ref.(name.Digest)
+			if !ok {
+				t.Done(fmt.Errorf("reference is not a tag or digest"))
```
Comment (saschagrunert) [inline pkg/spdx/implementation.go:347]:
```suggestion
				t.Done(errors.New("reference is not a tag or digest"))
```

File: pkg/spdx/implementation.go [hunk 2]
```diff
@@ -395,84 +331,56 @@ func (di *spdxDefaultImplementation) PullImagesToArchive(
...
-				}
-				var p string
-				ri := strings.Split(d.RepositoryStr(), "/")
-				if len(ri) > 0 {
-					p = fmt.Sprintf("%s_%s_%s", ri[0], ri[1], d.TagStr())
-				} else {
-					p = fmt.Sprintf("%s_%s", ri[0], d.TagStr())
-				}
+			p := strings.Split(d.DigestStr(), ":")
+			tarPath := filepath.Join(path, p[1]+".tar")
```
Comment (saschagrunert) [inline pkg/spdx/implementation.go:352]: Can we add a check to avoid causing a panic `if len(p) < 2`?

**Review by saschagrunert — COMMENTED** [review]
Just two nits, otherwise LGTM :+1:

File: pkg/spdx/implementation.go (hunk 2 above)
Comment (puerco) [reply pkg/spdx/implementation.go:356]: Nice catch, thanks @saschagrunert !

**Review by saschagrunert — APPROVED** [review]
